name: 'Setup Java JDK'
description: 'Sets up JDK 17 and Maven Cache'
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
